// 2026 World Cup venues (FIFA city-stadium names) from the published schedule.
// football-data.org's free tier omits the venue field, so the app falls back to
// this static map. Group games are keyed by the (sorted) team pair; knockout
// games by match number (73-104). Auto-generated — do not edit by hand.
import type { Fixture } from "./types";

export const GROUP_VENUES: Record<string, string> = {
  "Mexico|South Africa": "Mexico City Stadium",
  "Czechia|South Korea": "Guadalajara Stadium",
  "Bosnia and Herzegovina|Canada": "Toronto Stadium",
  "Paraguay|United States": "Los Angeles Stadium",
  "Qatar|Switzerland": "San Francisco Bay Area Stadium",
  "Brazil|Morocco": "New York/New Jersey Stadium",
  "Haiti|Scotland": "Boston Stadium",
  "Australia|Türkiye": "BC Place Vancouver",
  "Curaçao|Germany": "Houston Stadium",
  "Japan|Netherlands": "Dallas Stadium",
  "Ecuador|Ivory Coast": "Philadelphia Stadium",
  "Sweden|Tunisia": "Monterrey Stadium",
  "Cape Verde|Spain": "Atlanta Stadium",
  "Belgium|Egypt": "Seattle Stadium",
  "Saudi Arabia|Uruguay": "Miami Stadium",
  "Iran|New Zealand": "Los Angeles Stadium",
  "France|Senegal": "New York/New Jersey Stadium",
  "Iraq|Norway": "Boston Stadium",
  "Algeria|Argentina": "Kansas City Stadium",
  "Austria|Jordan": "San Francisco Bay Area Stadium",
  "DR Congo|Portugal": "Houston Stadium",
  "Croatia|England": "Dallas Stadium",
  "Ghana|Panama": "Toronto Stadium",
  "Colombia|Uzbekistan": "Mexico City Stadium",
  "Czechia|South Africa": "Atlanta Stadium",
  "Bosnia and Herzegovina|Switzerland": "Los Angeles Stadium",
  "Canada|Qatar": "BC Place Vancouver",
  "Mexico|South Korea": "Guadalajara Stadium",
  "Australia|United States": "Seattle Stadium",
  "Morocco|Scotland": "Boston Stadium",
  "Brazil|Haiti": "Philadelphia Stadium",
  "Paraguay|Türkiye": "San Francisco Bay Area Stadium",
  "Netherlands|Sweden": "Houston Stadium",
  "Germany|Ivory Coast": "Toronto Stadium",
  "Curaçao|Ecuador": "Kansas City Stadium",
  "Japan|Tunisia": "Monterrey Stadium",
  "Saudi Arabia|Spain": "Atlanta Stadium",
  "Belgium|Iran": "Los Angeles Stadium",
  "Cape Verde|Uruguay": "Miami Stadium",
  "Egypt|New Zealand": "BC Place Vancouver",
  "Argentina|Austria": "Dallas Stadium",
  "France|Iraq": "Philadelphia Stadium",
  "Norway|Senegal": "New York/New Jersey Stadium",
  "Algeria|Jordan": "San Francisco Bay Area Stadium",
  "Portugal|Uzbekistan": "Houston Stadium",
  "England|Ghana": "Boston Stadium",
  "Croatia|Panama": "Toronto Stadium",
  "Colombia|DR Congo": "Guadalajara Stadium",
  "Canada|Switzerland": "BC Place Vancouver",
  "Bosnia and Herzegovina|Qatar": "Seattle Stadium",
  "Brazil|Scotland": "Miami Stadium",
  "Haiti|Morocco": "Atlanta Stadium",
  "Czechia|Mexico": "Mexico City Stadium",
  "South Africa|South Korea": "Monterrey Stadium",
  "Curaçao|Ivory Coast": "Philadelphia Stadium",
  "Ecuador|Germany": "New York/New Jersey Stadium",
  "Japan|Sweden": "Dallas Stadium",
  "Netherlands|Tunisia": "Kansas City Stadium",
  "Türkiye|United States": "Los Angeles Stadium",
  "Australia|Paraguay": "San Francisco Bay Area Stadium",
  "France|Norway": "Boston Stadium",
  "Iraq|Senegal": "Toronto Stadium",
  "Cape Verde|Saudi Arabia": "Houston Stadium",
  "Spain|Uruguay": "Guadalajara Stadium",
  "Egypt|Iran": "Seattle Stadium",
  "Belgium|New Zealand": "BC Place Vancouver",
  "England|Panama": "New York/New Jersey Stadium",
  "Croatia|Ghana": "Philadelphia Stadium",
  "Colombia|Portugal": "Miami Stadium",
  "DR Congo|Uzbekistan": "Atlanta Stadium",
  "Algeria|Austria": "Kansas City Stadium",
  "Argentina|Jordan": "Dallas Stadium"
};

export const KO_VENUES: Record<number, string> = {
  "73": "Los Angeles Stadium",
  "74": "Boston Stadium",
  "75": "Monterrey Stadium",
  "76": "Houston Stadium",
  "77": "New York/New Jersey Stadium",
  "78": "Dallas Stadium",
  "79": "Mexico City Stadium",
  "80": "Atlanta Stadium",
  "81": "San Francisco Bay Area Stadium",
  "82": "Seattle Stadium",
  "83": "Toronto Stadium",
  "84": "Los Angeles Stadium",
  "85": "BC Place Vancouver",
  "86": "Miami Stadium",
  "87": "Kansas City Stadium",
  "88": "Dallas Stadium",
  "89": "Philadelphia Stadium",
  "90": "Houston Stadium",
  "91": "New York/New Jersey Stadium",
  "92": "Mexico City Stadium",
  "93": "Dallas Stadium",
  "94": "Seattle Stadium",
  "95": "Atlanta Stadium",
  "96": "BC Place Vancouver",
  "97": "Boston Stadium",
  "98": "Los Angeles Stadium",
  "99": "Miami Stadium",
  "100": "Kansas City Stadium",
  "101": "Dallas Stadium",
  "102": "Atlanta Stadium",
  "103": "Miami Stadium",
  "104": "New York/New Jersey Stadium"
};

/** Best venue for a fixture: the API value if present, else the static map. */
export function venueFor(f: Fixture): string | null {
  if (f.venue) return f.venue;
  if (f.stage === "GROUP") {
    if (!f.home_team || !f.away_team) return null;
    return GROUP_VENUES[[f.home_team, f.away_team].sort().join("|")] ?? null;
  }
  return KO_VENUES[f.match_no] ?? null;
}
